import { getSession } from "next-auth/react";
import Head from "next/head";
import { type ReactElement, useState, useEffect } from "react";
import { SignedInLayout } from "src/components";
import type { NextPageWithLayout } from './_app';
import { BiRefresh, BiCalculator } from 'react-icons/bi';
import { IoHelpSharp } from 'react-icons/io5';
import { BsPersonAdd } from 'react-icons/bs';

const Home: NextPageWithLayout = ({ user, clients }) => {
  const [filteredClients, setFilteredClients] = useState(clients)
  const [searchTerm, setSearchTerm] = useState('')

  useEffect(() => {
    const searchedClients = clients.filter((client) => {
      return `${client.firstName} ${client.lastName}`.includes(searchTerm)
    })

    setFilteredClients(searchedClients)
  }, [searchTerm])

  const { company } = user

  return (
    <>
      <Head>
        <title>Mortgage Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="drawer drawer-mobile">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col">
          <main className="px-10 py-16 ">
            <h1 className="text-4xl">
              {company.name}
            </h1>
            <div className="mt-6 flex justify-between items-center w-full">
              <h2 className="text-2xl">
                Client Renewals
              </h2>
              <div>
                <input
                  type="text"
                  placeholder="Search…"
                  className="input input-bordered border-slate-300"
                  onChange={(e) => {
                    console.log(e);
                    setSearchTerm(e.target.value)

                  }}
                />
              </div>
            </div>
            <table className="table w-full mt-5">
              <thead >
                <tr>
                  <th className="bg-slate-200">Name</th>
                  <th className="bg-slate-200">Phone</th>
                  <th className="bg-slate-200">Email</th>
                  <th className="bg-slate-200">Renewal Date</th>
                </tr>
              </thead>
              <tbody>
                {filteredClients.map((client) => (
                  <tr key={client.email}>
                    <td>{client.firstName} {client.lastName}</td>
                    <td>0{client.phone}</td>
                    <td>{client.email}</td>
                    <td>{new Date(client.renewalDate).toLocaleDateString('en-GB')}</td>
                  </tr>
                ))}

              </tbody>
            </table>
          </main>
          <label htmlFor="my-drawer-2" className="btn btn-primary drawer-button lg:hidden">Open drawer</label>

        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
          <ul className="menu p-4 bg-slate-100 text-base-content w-64">
            <li className="text-primary-focus"><a><BiRefresh size={20} /> Client Renewals</a></li>
            <li className="text-slate-400"><a><BsPersonAdd size={20} /> Add Client</a></li>
            <li className="text-slate-400"><a><BiCalculator size={20} /> Mortgage Calculator</a></li>
            <li className="text-slate-400"><a><IoHelpSharp size={20} /> Help</a></li>
          </ul>

        </div>
      </div>

    </>
  );
};

export async function getServerSideProps(context) {
  const session = await getSession(context)


  if (!session) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }

  const response = await fetch(`http://localhost:3000/api/user/${session.user.id}`)

  console.log('hereeee 111');
  const user = await response.json()
  console.log('hereeee 222');

  if (!user.companyMembershipId) {
    return {
      redirect: {
        destination: '/getting-started',
        permanent: false,
      },
    }
  }


  const clientsRes = await fetch(`http://localhost:3000/api/mortgageClients/${user.companyId}`)

  const clients = await clientsRes.json()

  console.log('clients server side', clients);

  return {
    props: { user, clients }
  }
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <SignedInLayout>{page}</SignedInLayout>
  )
}

export default Home;
